// Generated by https://quicktype.io

export class BusinessClass {
    id_cuenta:      number;
    cuenta_general: number;
    empresa:        string;
    mision:         string;
    vision:         string;
    descripcion:    string;
}
