// Generated by https://quicktype.io

export class User {
    id_cuenta:       number;
    user:            string;
    fecha_creacion:  string;
    pais:            string;
    telefono:        number;
    correo:          string;
    extension:       number;
    password:        string;
    verificado:      boolean;
    activa:          boolean;
    StandardAccount: StandardAccount | null;
}

export class StandardAccount {
    id_cuenta:        number;
    cuenta_general:   number;
    nombres:          string;
    apellidos:        string;
    fecha_nacimiento: string;
}

          