

// Generated by https://quicktype.io
export class Post {
    id:                number;
    cuenta:            number;
    titulo:            string;
    fecha_publicacion: string;
    costo:             Number;
    divisa:            string;
    intercambio:       boolean;
    descripcion:       string;
    activo:            boolean;
    invisible:         boolean;
}
    